version: "3.9"

services:
  db:
    image: postgres:16
    container_name: summer_plans_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: summer_plans
    ports:
      - "5432:5432"
    volumes:
      - summer_plans_db_data:/var/lib/postgresql/data

volumes:
  summer_plans_db_data: